# Generated by Django 5.2.2 on 2025-06-09 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_events',
            field=models.ManyToManyField(blank=True, to='events.event'),
        ),
    ]
