# Generated by Django 5.2.2 on 2025-06-09 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='tickets/')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.booking')),
            ],
        ),
    ]
